version: '3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: 'time-tracker-db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=mus'
      - 'POSTGRES_PASSWORD=mus'
      - 'POSTGRES_DB=test-db'